# Generated by Django 3.0.6 on 2020-11-07 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('silviacontrol', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='responsemodel',
            old_name='brewing',
            new_name='brew',
        ),
        migrations.RenameField(
            model_name='settingsmodel',
            old_name='pressure_setpoints',
            new_name='profile_pressure_setpoints',
        ),
        migrations.RenameField(
            model_name='settingsmodel',
            old_name='pressure_t_setpoints',
            new_name='profile_time_setpoints',
        ),
        migrations.RemoveField(
            model_name='settingsmodel',
            name='heater_kp_mode',
        ),
        migrations.RemoveField(
            model_name='settingsmodel',
            name='t_update',
        ),
    ]
