# Generated by Django 3.0.6 on 2020-11-07 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silviacontrol', '0002_auto_20201107_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsemodel',
            name='heater_duty',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='responsemodel',
            name='low_water',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='responsemodel',
            name='mass',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='responsemodel',
            name='pump_duty',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='responsemodel',
            name='temperature',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
